apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-twvi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0030-tenant/tkrw-pr712-0075-0030-app/devfile-sample-twvi@sha256:9f8d7723bd214d39df07513b3504d173b736e3e8eca5d4599bc60e1f433bdc98
        name: my-nodejs
        resources: {}
status: {}
